apiVersion: v1
kind: Service
metadata:
  name: hello
spec:
  type: LoadBalancer
  selector:
    app: hello
  ports:
  - port: 80
    targetPort: 8080

---
apiVersion: v1
kind: Pod
metadata:
  name: hello-gke-pod-1
  labels: 
      app: hello
      type: server
spec:
  hostname: helloendocode.test.com
  containers:
  - name: hello
    image: europe-west3-docker.pkg.dev/artifacts-339420/test/app:latest
    imagePullPolicy: Always
    resources:
      limits:
        memory: 512Mi
        cpu: "1"
      requests:
        memory: 256Mi
        cpu: "0.2"
  terminationGracePeriodSeconds: 30